### ISSUE TITLE
Issue in Tutorial 0 section.2 read_frame() 

### ISSUE THREAD

**Issue by ibrooabri** [gwastro/PyCBC-Tutorials#30]
read_frame() gives out an error: 

module 'lalframe' has no attribute 'FrSetMode'

I have run the code on the same colab notebook.

**Comment by ahnitz** [comment]
@ibrooabri Thanks for this report.

 Lalsuite (which provides lalframe) put out a release that made breaking changes two days ago. This is a library we depend on. We have just patched this on our side to avoid the functions they've removed, but we'll need to put out a new release to fix this. The short-term alternative is to use the previous release of lalsuite. You can do this by requiring version 7.11. You can do this with 

```
pip install lalsuite==7.11
```
In place of the install without a version specified. 

I'm hopefully we'll have a new release out soon, but hopefully this will help you out in the short term. 

Thanks for raising this issue here as I'm sure others might hit it and it's helpful for them to see what the possible solution is!

**Comment by ahnitz** [comment]
@ibrooabri We have just made a new release, so if you reinstall the latest version of pycbc the problem should be fixed. If you have an open notebook you made need to tell it to upgrade pycbc when it installs it (i.e. if an existing installation already exists where you are running the notebook).

**Comment by ibrooabri** [comment]
Thank you very much. It is working perfectly fine now. That is a great help!
